sudo: false
install: true
language: android
jdk: oraclejdk8
android:
  components:
    # needs to be first to get new package versions
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-google-m2repository
  licenses:
    - '.+'
    
# AS script
script:
  - 'bash ./gradlew assembleDebug check;'
  - 'bash ./gradlew app:assembleRelease check;'
  
 # Cache
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

# Notification
notifications:
  email: false

before_install:
  - 'yes | sdkmanager "platforms;android-27"'